services:
  postgres:
    image: postgres:16
    container_name: nfe_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PRISMA_USER}
      POSTGRES_PASSWORD: ${PRISMA_PASS}
      POSTGRES_DB: ${PRISMA_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRISMA_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nfe-service:
    build: ./
    container_name: nfe-service
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always


volumes:
  pgdata:
